repos:
  - repo: local
    hooks:
      - id: isort
        name: isort
        entry: pipenv run isort
        require_serial: true
        language: python
        language_version: python3
        types_or: [cython, pyi, python]
        args: ["--filter-files"]
        minimum_pre_commit_version: 2.9.2
      - id: black
        name: black
        entry: pipenv run black
        language: python
        minimum_pre_commit_version: 2.9.2
        require_serial: true
        types_or: [python, pyi]
      - id: flake8
        name: flake8
        entry: pipenv run flake8
        language: python
        types: [python]
        require_serial: true
      - id: tests
        name: Tests
        entry: make test
        always_run: true
        pass_filenames: false
        language: system
        types: [python]
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0
    hooks:
      - id: fix-byte-order-marker
      - id: end-of-file-fixer
      - id: trailing-whitespace
